version: '3.3'
services:
  nova_sanctum: &nova_sanctum
    image: nova_sanctum  # Use the built image name
    ipc: host
    network_mode: host
    privileged: true
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - $HOME/siddarth/shared/ros2:/root/shared/ros2
      - $HOME/.Xauthority:/tmp/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    command: ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /root/ros2_ws/install/setup.bash && tail -f /dev/null"]  # Keeps container running

  # collector:
  #   <<: *eclss_base
  #   container_name: collector
  #   command: ["ros2", "run", "demo_nova_sanctum", "collector"]

  # desiccant:
  #   <<: *eclss_base
  #   container_name: desiccant
  #   command: ["ros2", "run", "demo_nova_sanctum", "desiccant"]

  # adsorbent:
  #   <<: *eclss_base
  #   container_name: adsorbent
  #   command: ["ros2", "run", "demo_nova_sanctum", "adsorbent"]

  # sabatier:
  #   <<: *eclss_base
  #   container_name: sabatier
  #   command: ["ros2", "run", "demo_nova_sanctum", "sabatier"]

  # water_pub:
  #   <<: *eclss_base
  #   container_name: water_pub
  #   command: ["ros2", "run", "demo_nova_sanctum", "water_pub"]

  # deionization_bed:
  #   <<: *eclss_base
  #   container_name: deionization_bed
  #   command: ["ros2", "run", "demo_nova_sanctum", "deionization_bed"]

  # electrolysis:
  #   <<: *eclss_base
  #   container_name: electrolysis
  #   command: ["ros2", "run", "demo_nova_sanctum", "electrolysis"]

  # whc:
  #   <<: *eclss_base
  #   container_name: whc
  #   command: ["ros2", "run", "demo_nova_sanctum", "whc"]

  # waste_collector:
  #   <<: *eclss_base
  #   container_name: waste_collector
  #   command: ["ros2", "run", "demo_nova_sanctum", "waste_collector"]

  # upa:
  #   <<: *eclss_base
  #   container_name: upa
  #   command: ["ros2", "run", "demo_nova_sanctum", "upa"]

  # filter:
  #   <<: *eclss_base
  #   container_name: filter
  #   command: ["ros2", "run", "demo_nova_sanctum", "filter"]

  # catalytic_chamber:
  #   <<: *eclss_base
  #   container_name: catalytic_chamber
  #   command: ["ros2", "run", "demo_nova_sanctum", "catalytic_chamber"]

  # ionization:
  #   <<: *eclss_base
  #   container_name: ionization
  #   command: ["ros2", "run", "demo_nova_sanctum", "ionization"]

  # clean_water_tank:
  #   <<: *eclss_base
  #   container_name: clean_water_tank
  #   command: ["ros2", "run", "demo_nova_sanctum", "clean_water_tank"]

  # ultrasound:
  #   <<: *eclss_base
  #   container_name: ultrasound
  #   command: ["ros2", "run", "demo_nova_sanctum", "ultrasound"]
