/air_collector_node:
  ros__parameters:
    flow_rate: 28.0  # Flow rate in SCFM
    co2_intake: 1.04 # CO2 intake in mmHg
    crew_onboard: 4
    cabin_pressure: 14.7  # Cabin pressure in PSI
    temperature_cutoff: 450.0  # Temperature cutoff in Celsius
    max_crew_limit: 6
    power_consumption: 1.0  # Power in kW
    tank_capacity: 1000.0  # Air tank capacity in grams
    system_name: "demo_nova_sanctum"
    mode_of_operation: "standby"

    co2_threshold: 500.0
    moisture_threshold: 70.0
    contaminants_threshold: 30.0

    temp_kp: 0.1
    temp_ki: 0.01
    temp_kd: 0.005
    press_kp: 0.1
    press_ki: 0.01
    press_kd: 0.005

/desiccant_server:
  ros__parameters:
    moisture_removal_rate: 0.95
    contaminant_removal_rate: 0.90
    emergency_threshold: 5.0

/adsorbent_bed:
  ros__parameters:
    co2_removal_efficiency: 0.95
    co2_to_space_ratio: 0.40
    desired_temperature: 420.0
    temperature_tolerance: 30.0
    kp: 0.6
    kd: 0.15

/buchi_automaton:
  ros__parameters:
    never_claim: |
      never { /* G(!p4 & (!p0 | Fp1) & (!p1 | Fp2) & (!p2 | Fp3)) */
      accept_init:
        if
        :: (((!(p0)) && (!(p1)) && (!(p2)) && (!(p4))) || ((!(p0)) && (p2) && (p3) && (!(p4))) || ((p1) && (p2) && (p3) && (!(p4)))) -> goto accept_init
        :: (((!(p0)) && (p2) && (!(p3)) && (!(p4))) || ((p1) && (p2) && (!(p3)) && (!(p4)))) -> goto T0_S1
        :: ((p1) && (!(p2)) && (!(p4))) -> goto T0_S2
        :: (((p0) && (!(p1)) && (!(p2)) && (!(p4))) || ((p0) && (!(p1)) && (p3) && (!(p4)))) -> goto T0_S3
        :: ((p0) && (!(p1)) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S4
        fi;
      T0_S1:
        if
        :: (((!(p0)) && (!(p1)) && (p3) && (!(p4))) || ((p1) && (p2) && (p3) && (!(p4)))) -> goto accept_init
        :: (((!(p0)) && (!(p1)) && (!(p3)) && (!(p4))) || ((p1) && (p2) && (!(p3)) && (!(p4)))) -> goto T0_S1
        :: ((p1) && (!(p2)) && (p3) && (!(p4))) -> goto T0_S2
        :: ((p0) && (!(p1)) && (p3) && (!(p4))) -> goto T0_S3
        :: ((p0) && (!(p1)) && (!(p3)) && (!(p4))) -> goto T0_S4
        :: ((p1) && (!(p2)) && (!(p3)) && (!(p4))) -> goto T0_S5
        fi;
      T0_S2:
        if
        :: (((!(p0)) && (p2) && (p3) && (!(p4))) || ((p1) && (p2) && (p3) && (!(p4)))) -> goto accept_init
        :: (((!(p0)) && (!(p2)) && (!(p4))) || ((p1) && (!(p2)) && (!(p4)))) -> goto T0_S2
        :: ((p0) && (!(p1)) && (p2) && (p3) && (!(p4))) -> goto T0_S3
        :: (((!(p0)) && (p2) && (!(p3)) && (!(p4))) || ((p1) && (p2) && (!(p3)) && (!(p4)))) -> goto accept_S6
        :: ((p0) && (!(p1)) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S7
        :: ((p0) && (!(p1)) && (!(p2)) && (!(p4))) -> goto T0_S8
        fi;
      T0_S3:
        if
        :: ((p1) && (p2) && (p3) && (!(p4))) -> goto accept_init
        :: (((!(p1)) && (!(p2)) && (!(p4))) || ((!(p1)) && (p3) && (!(p4)))) -> goto T0_S3
        :: ((p1) && (p2) && (!(p3)) && (!(p4))) -> goto accept_S6
        :: ((!(p1)) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S7
        :: ((p1) && (!(p2)) && (!(p4))) -> goto accept_S9
        fi;
      T0_S4:
        if
        :: ((p1) && (p2) && (p3) && (!(p4))) -> goto accept_init
        :: ((p1) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S1
        :: ((p1) && (!(p2)) && (p3) && (!(p4))) -> goto T0_S2
        :: ((!(p1)) && (p3) && (!(p4))) -> goto T0_S3
        :: ((!(p1)) && (!(p3)) && (!(p4))) -> goto T0_S4
        :: ((p1) && (!(p2)) && (!(p3)) && (!(p4))) -> goto T0_S5
        fi;
      T0_S5:
        if
        :: (((!(p0)) && (p2) && (p3) && (!(p4))) || ((p1) && (p2) && (p3) && (!(p4)))) -> goto accept_init
        :: (((!(p0)) && (p2) && (!(p3)) && (!(p4))) || ((p1) && (p2) && (!(p3)) && (!(p4)))) -> goto T0_S1
        :: (((!(p0)) && (!(p2)) && (p3) && (!(p4))) || ((p1) && (!(p2)) && (p3) && (!(p4)))) -> goto T0_S2
        :: ((p0) && (!(p1)) && (p2) && (p3) && (!(p4))) -> goto T0_S3
        :: ((p0) && (!(p1)) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S4
        :: (((!(p0)) && (!(p2)) && (!(p3)) && (!(p4))) || ((p1) && (!(p2)) && (!(p3)) && (!(p4)))) -> goto T0_S5
        :: ((p0) && (!(p1)) && (!(p2)) && (p3) && (!(p4))) -> goto T0_S8
        :: ((p0) && (!(p1)) && (!(p2)) && (!(p3)) && (!(p4))) -> goto T0_S10
        fi;
      accept_S6:
        if
        :: (((!(p0)) && (!(p1)) && (p3) && (!(p4))) || ((p1) && (p2) && (p3) && (!(p4)))) -> goto accept_init
        :: (((!(p0)) && (!(p1)) && (!(p3)) && (!(p4))) || ((p1) && (p2) && (!(p3)) && (!(p4)))) -> goto T0_S1
        :: ((p1) && (!(p2)) && (p3) && (!(p4))) -> goto T0_S2
        :: ((p0) && (!(p1)) && (p3) && (!(p4))) -> goto T0_S3
        :: ((p0) && (!(p1)) && (!(p3)) && (!(p4))) -> goto T0_S4
        :: ((p1) && (!(p2)) && (!(p3)) && (!(p4))) -> goto T0_S5
        fi;
      T0_S7:
        if
        :: ((p1) && (p2) && (p3) && (!(p4))) -> goto accept_init
        :: ((!(p1)) && (p3) && (!(p4))) -> goto T0_S3
        :: ((p1) && (p2) && (!(p3)) && (!(p4))) -> goto accept_S6
        :: ((!(p1)) && (!(p3)) && (!(p4))) -> goto T0_S7
        :: ((p1) && (!(p2)) && (p3) && (!(p4))) -> goto accept_S9
        :: ((p1) && (!(p2)) && (!(p3)) && (!(p4))) -> goto accept_S11
        fi;
      T0_S8:
        if
        :: ((p1) && (p2) && (p3) && (!(p4))) -> goto accept_init
        :: ((p1) && (!(p2)) && (!(p4))) -> goto T0_S2
        :: ((!(p1)) && (p2) && (p3) && (!(p4))) -> goto T0_S3
        :: ((p1) && (p2) && (!(p3)) && (!(p4))) -> goto accept_S6
        :: ((!(p1)) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S7
        :: ((!(p1)) && (!(p2)) && (!(p4))) -> goto T0_S8
        fi;
      accept_S9:
        if
        :: (((!(p0)) && (p2) && (p3) && (!(p4))) || ((p1) && (p2) && (p3) && (!(p4)))) -> goto accept_init
        :: (((!(p0)) && (p2) && (!(p3)) && (!(p4))) || ((p1) && (p2) && (!(p3)) && (!(p4)))) -> goto T0_S1
        :: (((!(p0)) && (!(p2)) && (!(p4))) || ((p1) && (!(p2)) && (!(p4)))) -> goto T0_S2
        :: ((p0) && (!(p1)) && (p2) && (p3) && (!(p4))) -> goto T0_S3
        :: ((p0) && (!(p1)) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S4
        :: ((p0) && (!(p1)) && (!(p2)) && (!(p4))) -> goto T0_S8
        fi;
      T0_S10:
        if
        :: ((p1) && (p2) && (p3) && (!(p4))) -> goto accept_init
        :: ((p1) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S1
        :: ((p1) && (!(p2)) && (p3) && (!(p4))) -> goto T0_S2
        :: ((!(p1)) && (p2) && (p3) && (!(p4))) -> goto T0_S3
        :: ((!(p1)) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S4
        :: ((p1) && (!(p2)) && (!(p3)) && (!(p4))) -> goto T0_S5
        :: ((!(p1)) && (!(p2)) && (p3) && (!(p4))) -> goto T0_S8
        :: ((!(p1)) && (!(p2)) && (!(p3)) && (!(p4))) -> goto T0_S10
        fi;
      accept_S11:
        if
        :: (((!(p0)) && (p2) && (p3) && (!(p4))) || ((p1) && (p2) && (p3) && (!(p4)))) -> goto accept_init
        :: (((!(p0)) && (p2) && (!(p3)) && (!(p4))) || ((p1) && (p2) && (!(p3)) && (!(p4)))) -> goto T0_S1
        :: (((!(p0)) && (!(p2)) && (p3) && (!(p4))) || ((p1) && (!(p2)) && (p3) && (!(p4)))) -> goto T0_S2
        :: ((p0) && (!(p1)) && (p2) && (p3) && (!(p4))) -> goto T0_S3
        :: ((p0) && (!(p1)) && (p2) && (!(p3)) && (!(p4))) -> goto T0_S4
        :: (((!(p0)) && (!(p2)) && (!(p3)) && (!(p4))) || ((p1) && (!(p2)) && (!(p3)) && (!(p4)))) -> goto T0_S5
        :: ((p0) && (!(p1)) && (!(p2)) && (p3) && (!(p4))) -> goto T0_S8
        :: ((p0) && (!(p1)) && (!(p2)) && (!(p3)) && (!(p4))) -> goto T0_S10
        fi;
      }